---
language: node_js
node_js:
  - "8.9.4"
sudo: false

cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-beta

before_install:
  - yarn add bower

install:
  - yarn install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
